#! /usr/bin/perl
use warnings;
use strict;

use POSIX qw(strerror);

#
# Wrapper for AFS's translate_et that tries the Kerberos errors too.
# I got said errors from the krb5.h on my Snow Leopard Mac...
#

# Copyright 1989,1990,1995,2001, 2003, 2007  by the Massachusetts Institute of Technology.
# All Rights Reserved.
#
# Export of this software from the United States of America may
#   require a specific license from the United States Government.
#   It is the responsibility of any person or organization contemplating
#   export to obtain such a license before exporting.
# 
# WITHIN THAT CONSTRAINT, permission to use, copy, modify, and
# distribute this software and its documentation for any purpose and
# without fee is hereby granted, provided that the above copyright
# notice appear in all copies and that both that copyright notice and
# this permission notice appear in supporting documentation, and that
# the name of M.I.T. not be used in advertising or publicity pertaining
# to distribution of the software without specific, written prior
# permission.	Furthermore if you modify this software you must label
# your software as modified software and not distribute it in such a
# fashion that it might be confused with the original M.I.T. software.
# M.I.T. makes no representations about the suitability of
# this software for any purpose.  It is provided "as is" without express
# or implied warranty.
my %krberr = (
	      -1765328384 => 'KRB5KDC_ERR_NONE',
	      -1765328383 => 'KRB5KDC_ERR_NAME_EXP',
              -1765328382 => 'KRB5KDC_ERR_SERVICE_EXP',
              -1765328381 => 'KRB5KDC_ERR_BAD_PVNO',
              -1765328380 => 'KRB5KDC_ERR_C_OLD_MAST_KVNO',
              -1765328379 => 'KRB5KDC_ERR_S_OLD_MAST_KVNO',
              -1765328378 => 'KRB5KDC_ERR_C_PRINCIPAL_UNKNOWN',
              -1765328377 => 'KRB5KDC_ERR_S_PRINCIPAL_UNKNOWN',
              -1765328376 => 'KRB5KDC_ERR_PRINCIPAL_NOT_UNIQUE',
              -1765328375 => 'KRB5KDC_ERR_NULL_KEY',
              -1765328374 => 'KRB5KDC_ERR_CANNOT_POSTDATE',
              -1765328373 => 'KRB5KDC_ERR_NEVER_VALID',
              -1765328372 => 'KRB5KDC_ERR_POLICY',
              -1765328371 => 'KRB5KDC_ERR_BADOPTION',
              -1765328370 => 'KRB5KDC_ERR_ETYPE_NOSUPP',
              -1765328369 => 'KRB5KDC_ERR_SUMTYPE_NOSUPP',
              -1765328368 => 'KRB5KDC_ERR_PADATA_TYPE_NOSUPP',
              -1765328367 => 'KRB5KDC_ERR_TRTYPE_NOSUPP',
              -1765328366 => 'KRB5KDC_ERR_CLIENT_REVOKED',
              -1765328365 => 'KRB5KDC_ERR_SERVICE_REVOKED',
              -1765328364 => 'KRB5KDC_ERR_TGT_REVOKED',
              -1765328363 => 'KRB5KDC_ERR_CLIENT_NOTYET',
              -1765328362 => 'KRB5KDC_ERR_SERVICE_NOTYET',
              -1765328361 => 'KRB5KDC_ERR_KEY_EXP',
              -1765328360 => 'KRB5KDC_ERR_PREAUTH_FAILED',
              -1765328359 => 'KRB5KDC_ERR_PREAUTH_REQUIRED',
              -1765328358 => 'KRB5KDC_ERR_SERVER_NOMATCH',
              -1765328357 => 'KRB5KDC_ERR_MUST_USE_USER2USER',
              -1765328356 => 'KRB5KDC_ERR_PATH_NOT_ACCEPTED',
              -1765328355 => 'KRB5KDC_ERR_SVC_UNAVAILABLE',
              -1765328354 => 'KRB5PLACEHOLD_30',
              -1765328353 => 'KRB5KRB_AP_ERR_BAD_INTEGRITY',
              -1765328352 => 'KRB5KRB_AP_ERR_TKT_EXPIRED',
              -1765328351 => 'KRB5KRB_AP_ERR_TKT_NYV',
              -1765328350 => 'KRB5KRB_AP_ERR_REPEAT',
              -1765328349 => 'KRB5KRB_AP_ERR_NOT_US',
              -1765328348 => 'KRB5KRB_AP_ERR_BADMATCH',
              -1765328347 => 'KRB5KRB_AP_ERR_SKEW',
              -1765328346 => 'KRB5KRB_AP_ERR_BADADDR',
              -1765328345 => 'KRB5KRB_AP_ERR_BADVERSION',
              -1765328344 => 'KRB5KRB_AP_ERR_MSG_TYPE',
              -1765328343 => 'KRB5KRB_AP_ERR_MODIFIED',
              -1765328342 => 'KRB5KRB_AP_ERR_BADORDER',
              -1765328341 => 'KRB5KRB_AP_ERR_ILL_CR_TKT',
              -1765328340 => 'KRB5KRB_AP_ERR_BADKEYVER',
              -1765328339 => 'KRB5KRB_AP_ERR_NOKEY',
              -1765328338 => 'KRB5KRB_AP_ERR_MUT_FAIL',
              -1765328337 => 'KRB5KRB_AP_ERR_BADDIRECTION',
              -1765328336 => 'KRB5KRB_AP_ERR_METHOD',
              -1765328335 => 'KRB5KRB_AP_ERR_BADSEQ',
              -1765328334 => 'KRB5KRB_AP_ERR_INAPP_CKSUM',
              -1765328333 => 'KRB5KRB_AP_PATH_NOT_ACCEPTED',
              -1765328332 => 'KRB5KRB_ERR_RESPONSE_TOO_BIG',
              -1765328331 => 'KRB5PLACEHOLD_53',
              -1765328330 => 'KRB5PLACEHOLD_54',
              -1765328329 => 'KRB5PLACEHOLD_55',
              -1765328328 => 'KRB5PLACEHOLD_56',
              -1765328327 => 'KRB5PLACEHOLD_57',
              -1765328326 => 'KRB5PLACEHOLD_58',
              -1765328325 => 'KRB5PLACEHOLD_59',
              -1765328324 => 'KRB5KRB_ERR_GENERIC',
              -1765328323 => 'KRB5KRB_ERR_FIELD_TOOLONG',
              -1765328322 => 'KRB5KDC_ERR_CLIENT_NOT_TRUSTED',
              -1765328321 => 'KRB5KDC_ERR_KDC_NOT_TRUSTED',
              -1765328320 => 'KRB5KDC_ERR_INVALID_SIG',
              -1765328319 => 'KRB5KDC_ERR_DH_KEY_PARAMETERS_NOT_ACCEPTED',
              -1765328318 => 'KRB5KDC_ERR_CERTIFICATE_MISMATCH',
              -1765328317 => 'KRB5KRB_AP_ERR_NO_TGT',
              -1765328316 => 'KRB5KDC_ERR_WRONG_REALM',
              -1765328315 => 'KRB5KRB_AP_ERR_USER_TO_USER_REQUIRED',
              -1765328314 => 'KRB5KDC_ERR_CANT_VERIFY_CERTIFICATE',
              -1765328313 => 'KRB5KDC_ERR_INVALID_CERTIFICATE',
              -1765328312 => 'KRB5KDC_ERR_REVOKED_CERTIFICATE',
              -1765328311 => 'KRB5KDC_ERR_REVOCATION_STATUS_UNKNOWN',
              -1765328310 => 'KRB5KDC_ERR_REVOCATION_STATUS_UNAVAILABLE',
              -1765328309 => 'KRB5KDC_ERR_CLIENT_NAME_MISMATCH',
              -1765328308 => 'KRB5KDC_ERR_KDC_NAME_MISMATCH',
              -1765328307 => 'KRB5KDC_ERR_INCONSISTENT_KEY_PURPOSE',
              -1765328306 => 'KRB5KDC_ERR_DIGEST_IN_CERT_NOT_ACCEPTED',
              -1765328305 => 'KRB5KDC_ERR_PA_CHECKSUM_MUST_BE_INCLUDED',
              -1765328304 => 'KRB5KDC_ERR_DIGEST_IN_SIGNED_DATA_NOT_ACCEPTED',
              -1765328303 => 'KRB5KDC_ERR_PUBLIC_KEY_ENCRYPTION_NOT_SUPPORTED',
              -1765328302 => 'KRB5PLACEHOLD_82',
              -1765328301 => 'KRB5PLACEHOLD_83',
              -1765328300 => 'KRB5PLACEHOLD_84',
              -1765328299 => 'KRB5PLACEHOLD_85',
              -1765328298 => 'KRB5PLACEHOLD_86',
              -1765328297 => 'KRB5PLACEHOLD_87',
              -1765328296 => 'KRB5PLACEHOLD_88',
              -1765328295 => 'KRB5PLACEHOLD_89',
              -1765328294 => 'KRB5PLACEHOLD_90',
              -1765328293 => 'KRB5PLACEHOLD_91',
              -1765328292 => 'KRB5PLACEHOLD_92',
              -1765328291 => 'KRB5PLACEHOLD_93',
              -1765328290 => 'KRB5PLACEHOLD_94',
              -1765328289 => 'KRB5PLACEHOLD_95',
              -1765328288 => 'KRB5PLACEHOLD_96',
              -1765328287 => 'KRB5PLACEHOLD_97',
              -1765328286 => 'KRB5PLACEHOLD_98',
              -1765328285 => 'KRB5PLACEHOLD_99',
              -1765328284 => 'KRB5PLACEHOLD_100',
              -1765328283 => 'KRB5PLACEHOLD_101',
              -1765328282 => 'KRB5PLACEHOLD_102',
              -1765328281 => 'KRB5PLACEHOLD_103',
              -1765328280 => 'KRB5PLACEHOLD_104',
              -1765328279 => 'KRB5PLACEHOLD_105',
              -1765328278 => 'KRB5PLACEHOLD_106',
              -1765328277 => 'KRB5PLACEHOLD_107',
              -1765328276 => 'KRB5PLACEHOLD_108',
              -1765328275 => 'KRB5PLACEHOLD_109',
              -1765328274 => 'KRB5PLACEHOLD_110',
              -1765328273 => 'KRB5PLACEHOLD_111',
              -1765328272 => 'KRB5PLACEHOLD_112',
              -1765328271 => 'KRB5PLACEHOLD_113',
              -1765328270 => 'KRB5PLACEHOLD_114',
              -1765328269 => 'KRB5PLACEHOLD_115',
              -1765328268 => 'KRB5PLACEHOLD_116',
              -1765328267 => 'KRB5PLACEHOLD_117',
              -1765328266 => 'KRB5PLACEHOLD_118',
              -1765328265 => 'KRB5PLACEHOLD_119',
              -1765328264 => 'KRB5PLACEHOLD_120',
              -1765328263 => 'KRB5PLACEHOLD_121',
              -1765328262 => 'KRB5PLACEHOLD_122',
              -1765328261 => 'KRB5PLACEHOLD_123',
              -1765328260 => 'KRB5PLACEHOLD_124',
              -1765328259 => 'KRB5PLACEHOLD_125',
              -1765328258 => 'KRB5PLACEHOLD_126',
              -1765328257 => 'KRB5PLACEHOLD_127',
              -1765328256 => 'KRB5_ERR_RCSID',
              -1765328255 => 'KRB5_LIBOS_BADLOCKFLAG',
              -1765328254 => 'KRB5_LIBOS_CANTREADPWD',
              -1765328253 => 'KRB5_LIBOS_BADPWDMATCH',
              -1765328252 => 'KRB5_LIBOS_PWDINTR',
              -1765328251 => 'KRB5_PARSE_ILLCHAR',
              -1765328250 => 'KRB5_PARSE_MALFORMED',
              -1765328249 => 'KRB5_CONFIG_CANTOPEN',
              -1765328248 => 'KRB5_CONFIG_BADFORMAT',
              -1765328247 => 'KRB5_CONFIG_NOTENUFSPACE',
              -1765328246 => 'KRB5_BADMSGTYPE',
              -1765328245 => 'KRB5_CC_BADNAME',
              -1765328244 => 'KRB5_CC_UNKNOWN_TYPE',
              -1765328243 => 'KRB5_CC_NOTFOUND',
              -1765328242 => 'KRB5_CC_END',
              -1765328241 => 'KRB5_NO_TKT_SUPPLIED',
              -1765328240 => 'KRB5KRB_AP_WRONG_PRINC',
              -1765328239 => 'KRB5KRB_AP_ERR_TKT_INVALID',
              -1765328238 => 'KRB5_PRINC_NOMATCH',
              -1765328237 => 'KRB5_KDCREP_MODIFIED',
              -1765328236 => 'KRB5_KDCREP_SKEW',
              -1765328235 => 'KRB5_IN_TKT_REALM_MISMATCH',
              -1765328234 => 'KRB5_PROG_ETYPE_NOSUPP',
              -1765328233 => 'KRB5_PROG_KEYTYPE_NOSUPP',
              -1765328232 => 'KRB5_WRONG_ETYPE',
              -1765328231 => 'KRB5_PROG_SUMTYPE_NOSUPP',
              -1765328230 => 'KRB5_REALM_UNKNOWN',
              -1765328229 => 'KRB5_SERVICE_UNKNOWN',
              -1765328228 => 'KRB5_KDC_UNREACH',
              -1765328227 => 'KRB5_NO_LOCALNAME',
              -1765328226 => 'KRB5_MUTUAL_FAILED',
              -1765328225 => 'KRB5_RC_TYPE_EXISTS',
              -1765328224 => 'KRB5_RC_MALLOC',
              -1765328223 => 'KRB5_RC_TYPE_NOTFOUND',
              -1765328222 => 'KRB5_RC_UNKNOWN',
              -1765328221 => 'KRB5_RC_REPLAY',
              -1765328220 => 'KRB5_RC_IO',
              -1765328219 => 'KRB5_RC_NOIO',
              -1765328218 => 'KRB5_RC_PARSE',
              -1765328217 => 'KRB5_RC_IO_EOF',
              -1765328216 => 'KRB5_RC_IO_MALLOC',
              -1765328215 => 'KRB5_RC_IO_PERM',
              -1765328214 => 'KRB5_RC_IO_IO',
              -1765328213 => 'KRB5_RC_IO_UNKNOWN',
              -1765328212 => 'KRB5_RC_IO_SPACE',
              -1765328211 => 'KRB5_TRANS_CANTOPEN',
              -1765328210 => 'KRB5_TRANS_BADFORMAT',
              -1765328209 => 'KRB5_LNAME_CANTOPEN',
              -1765328208 => 'KRB5_LNAME_NOTRANS',
              -1765328207 => 'KRB5_LNAME_BADFORMAT',
              -1765328206 => 'KRB5_CRYPTO_INTERNAL',
              -1765328205 => 'KRB5_KT_BADNAME',
              -1765328204 => 'KRB5_KT_UNKNOWN_TYPE',
              -1765328203 => 'KRB5_KT_NOTFOUND',
              -1765328202 => 'KRB5_KT_END',
              -1765328201 => 'KRB5_KT_NOWRITE',
              -1765328200 => 'KRB5_KT_IOERR',
              -1765328199 => 'KRB5_NO_TKT_IN_RLM',
              -1765328198 => 'KRB5DES_BAD_KEYPAR',
              -1765328197 => 'KRB5DES_WEAK_KEY',
              -1765328196 => 'KRB5_BAD_ENCTYPE',
              -1765328195 => 'KRB5_BAD_KEYSIZE',
              -1765328194 => 'KRB5_BAD_MSIZE',
              -1765328193 => 'KRB5_CC_TYPE_EXISTS',
              -1765328192 => 'KRB5_KT_TYPE_EXISTS',
              -1765328191 => 'KRB5_CC_IO',
              -1765328190 => 'KRB5_FCC_PERM',
              -1765328189 => 'KRB5_FCC_NOFILE',
              -1765328188 => 'KRB5_FCC_INTERNAL',
              -1765328187 => 'KRB5_CC_WRITE',
              -1765328186 => 'KRB5_CC_NOMEM',
              -1765328185 => 'KRB5_CC_FORMAT',
              -1765328184 => 'KRB5_CC_NOT_KTYPE',
              -1765328183 => 'KRB5_INVALID_FLAGS',
              -1765328182 => 'KRB5_NO_2ND_TKT',
              -1765328181 => 'KRB5_NOCREDS_SUPPLIED',
              -1765328180 => 'KRB5_SENDAUTH_BADAUTHVERS',
              -1765328179 => 'KRB5_SENDAUTH_BADAPPLVERS',
              -1765328178 => 'KRB5_SENDAUTH_BADRESPONSE',
              -1765328177 => 'KRB5_SENDAUTH_REJECTED',
              -1765328176 => 'KRB5_PREAUTH_BAD_TYPE',
              -1765328175 => 'KRB5_PREAUTH_NO_KEY',
              -1765328174 => 'KRB5_PREAUTH_FAILED',
              -1765328173 => 'KRB5_RCACHE_BADVNO',
              -1765328172 => 'KRB5_CCACHE_BADVNO',
              -1765328171 => 'KRB5_KEYTAB_BADVNO',
              -1765328170 => 'KRB5_PROG_ATYPE_NOSUPP',
              -1765328169 => 'KRB5_RC_REQUIRED',
              -1765328168 => 'KRB5_ERR_BAD_HOSTNAME',
              -1765328167 => 'KRB5_ERR_HOST_REALM_UNKNOWN',
              -1765328166 => 'KRB5_SNAME_UNSUPP_NAMETYPE',
              -1765328165 => 'KRB5KRB_AP_ERR_V4_REPLY',
              -1765328164 => 'KRB5_REALM_CANT_RESOLVE',
              -1765328163 => 'KRB5_TKT_NOT_FORWARDABLE',
              -1765328162 => 'KRB5_FWD_BAD_PRINCIPAL',
              -1765328161 => 'KRB5_GET_IN_TKT_LOOP',
              -1765328160 => 'KRB5_CONFIG_NODEFREALM',
              -1765328159 => 'KRB5_SAM_UNSUPPORTED',
              -1765328158 => 'KRB5_SAM_INVALID_ETYPE',
              -1765328157 => 'KRB5_SAM_NO_CHECKSUM',
              -1765328156 => 'KRB5_SAM_BAD_CHECKSUM',
              -1765328155 => 'KRB5_KT_NAME_TOOLONG',
              -1765328154 => 'KRB5_KT_KVNONOTFOUND',
              -1765328153 => 'KRB5_APPL_EXPIRED',
              -1765328152 => 'KRB5_LIB_EXPIRED',
              -1765328151 => 'KRB5_CHPW_PWDNULL',
              -1765328150 => 'KRB5_CHPW_FAIL',
              -1765328149 => 'KRB5_KT_FORMAT',
              -1765328148 => 'KRB5_NOPERM_ETYPE',
              -1765328147 => 'KRB5_CONFIG_ETYPE_NOSUPP',
              -1765328146 => 'KRB5_OBSOLETE_FN',
              -1765328145 => 'KRB5_EAI_FAIL',
              -1765328144 => 'KRB5_EAI_NODATA',
              -1765328143 => 'KRB5_EAI_NONAME',
              -1765328142 => 'KRB5_EAI_SERVICE',
              -1765328141 => 'KRB5_ERR_NUMERIC_REALM',
              -1765328140 => 'KRB5_ERR_BAD_S2K_PARAMS',
              -1765328139 => 'KRB5_ERR_NO_SERVICE',
              -1765328138 => 'KRB5_CC_READONLY',
              -1765328137 => 'KRB5_CC_NOSUPP',
              -1765328136 => 'KRB5_DELTAT_BADFORMAT',
              -1765328135 => 'KRB5_PLUGIN_NO_HANDLE',
              -1765328134 => 'KRB5_PLUGIN_OP_NOTSUPP',

              -1780008448 => 'KRB5_KDB_RCSID',
              -1780008447 => 'KRB5_KDB_INUSE',
              -1780008446 => 'KRB5_KDB_UK_SERROR',
              -1780008445 => 'KRB5_KDB_UK_RERROR',
              -1780008444 => 'KRB5_KDB_UNAUTH',
              -1780008443 => 'KRB5_KDB_NOENTRY',
              -1780008442 => 'KRB5_KDB_ILL_WILDCARD',
              -1780008441 => 'KRB5_KDB_DB_INUSE',
              -1780008440 => 'KRB5_KDB_DB_CHANGED',
              -1780008439 => 'KRB5_KDB_TRUNCATED_RECORD',
              -1780008438 => 'KRB5_KDB_RECURSIVELOCK',
              -1780008437 => 'KRB5_KDB_NOTLOCKED',
              -1780008436 => 'KRB5_KDB_BADLOCKMODE',
              -1780008435 => 'KRB5_KDB_DBNOTINITED',
              -1780008434 => 'KRB5_KDB_DBINITED',
              -1780008433 => 'KRB5_KDB_ILLDIRECTION',
              -1780008432 => 'KRB5_KDB_NOMASTERKEY',
              -1780008431 => 'KRB5_KDB_BADMASTERKEY',
              -1780008430 => 'KRB5_KDB_INVALIDKEYSIZE',
              -1780008429 => 'KRB5_KDB_CANTREAD_STORED',
              -1780008428 => 'KRB5_KDB_BADSTORED_MKEY',
              -1780008427 => 'KRB5_KDB_CANTLOCK_DB',
              -1780008426 => 'KRB5_KDB_DB_CORRUPT',
              -1780008425 => 'KRB5_KDB_BAD_VERSION',
              -1780008424 => 'KRB5_KDB_BAD_SALTTYPE',
              -1780008423 => 'KRB5_KDB_BAD_ENCTYPE',
              -1780008422 => 'KRB5_KDB_BAD_CREATEFLAGS',
              -1780008421 => 'KRB5_KDB_NO_PERMITTED_KEY',
              -1780008420 => 'KRB5_KDB_NO_MATCHING_KEY',
              -1780008419 => 'KRB5_KDB_DBTYPE_NOTFOUND',
              -1780008418 => 'KRB5_KDB_DBTYPE_NOSUP',
              -1780008417 => 'KRB5_KDB_DBTYPE_INIT',
              -1780008416 => 'KRB5_KDB_SERVER_INTERNAL_ERR',
              -1780008415 => 'KRB5_KDB_ACCESS_ERROR',
              -1780008414 => 'KRB5_KDB_INTERNAL_ERROR',
              -1780008413 => 'KRB5_KDB_CONSTRAINT_VIOLATION',
              -1780008412 => 'KRB5_LOG_CONV',
              -1780008411 => 'KRB5_LOG_UNSTABLE',
              -1780008410 => 'KRB5_LOG_CORRUPT',
              -1780008409 => 'KRB5_LOG_ERROR',

              -1760647424 => 'KV5M_NONE',
              -1760647423 => 'KV5M_PRINCIPAL',
              -1760647422 => 'KV5M_DATA',
              -1760647421 => 'KV5M_KEYBLOCK',
              -1760647420 => 'KV5M_CHECKSUM',
              -1760647419 => 'KV5M_ENCRYPT_BLOCK',
              -1760647418 => 'KV5M_ENC_DATA',
              -1760647417 => 'KV5M_CRYPTOSYSTEM_ENTRY',
              -1760647416 => 'KV5M_CS_TABLE_ENTRY',
              -1760647415 => 'KV5M_CHECKSUM_ENTRY',
              -1760647414 => 'KV5M_AUTHDATA',
              -1760647413 => 'KV5M_TRANSITED',
              -1760647412 => 'KV5M_ENC_TKT_PART',
              -1760647411 => 'KV5M_TICKET',
              -1760647410 => 'KV5M_AUTHENTICATOR',
              -1760647409 => 'KV5M_TKT_AUTHENT',
              -1760647408 => 'KV5M_CREDS',
              -1760647407 => 'KV5M_LAST_REQ_ENTRY',
              -1760647406 => 'KV5M_PA_DATA',
              -1760647405 => 'KV5M_KDC_REQ',
              -1760647404 => 'KV5M_ENC_KDC_REP_PART',
              -1760647403 => 'KV5M_KDC_REP',
              -1760647402 => 'KV5M_ERROR',
              -1760647401 => 'KV5M_AP_REQ',
              -1760647400 => 'KV5M_AP_REP',
              -1760647399 => 'KV5M_AP_REP_ENC_PART',
              -1760647398 => 'KV5M_RESPONSE',
              -1760647397 => 'KV5M_SAFE',
              -1760647396 => 'KV5M_PRIV',
              -1760647395 => 'KV5M_PRIV_ENC_PART',
              -1760647394 => 'KV5M_CRED',
              -1760647393 => 'KV5M_CRED_INFO',
              -1760647392 => 'KV5M_CRED_ENC_PART',
              -1760647391 => 'KV5M_PWD_DATA',
              -1760647390 => 'KV5M_ADDRESS',
              -1760647389 => 'KV5M_KEYTAB_ENTRY',
              -1760647388 => 'KV5M_CONTEXT',
              -1760647387 => 'KV5M_OS_CONTEXT',
              -1760647386 => 'KV5M_ALT_METHOD',
              -1760647385 => 'KV5M_ETYPE_INFO_ENTRY',
              -1760647384 => 'KV5M_DB_CONTEXT',
              -1760647383 => 'KV5M_AUTH_CONTEXT',
              -1760647382 => 'KV5M_KEYTAB',
              -1760647381 => 'KV5M_RCACHE',
              -1760647380 => 'KV5M_CCACHE',
              -1760647379 => 'KV5M_PREAUTH_OPS',
              -1760647378 => 'KV5M_SAM_CHALLENGE',
              -1760647377 => 'KV5M_SAM_CHALLENGE_2',
              -1760647376 => 'KV5M_SAM_KEY',
              -1760647375 => 'KV5M_ENC_SAM_RESPONSE_ENC',
              -1760647374 => 'KV5M_ENC_SAM_RESPONSE_ENC_2',
              -1760647373 => 'KV5M_SAM_RESPONSE',
              -1760647372 => 'KV5M_SAM_RESPONSE_2',
              -1760647371 => 'KV5M_PREDICTED_SAM_RESPONSE',
              -1760647370 => 'KV5M_PASSWD_PHRASE_ELEMENT',
              -1760647369 => 'KV5M_GSS_OID',
              -1760647368 => 'KV5M_GSS_QUEUE',

              -1750206208 => 'KRB524_BADKEY',
              -1750206207 => 'KRB524_BADADDR',
              -1750206206 => 'KRB524_BADPRINC',
              -1750206205 => 'KRB524_BADREALM',
              -1750206204 => 'KRB524_V4ERR',
              -1750206203 => 'KRB524_ENCFULL',
              -1750206202 => 'KRB524_DECEMPTY',
              -1750206201 => 'KRB524_NOTRESP',
              -1750206200 => 'KRB524_KRB4_DISABLED',
               1859794432 => 'ASN1_BAD_TIMEFORMAT',
               1859794433 => 'ASN1_MISSING_FIELD',
               1859794434 => 'ASN1_MISPLACED_FIELD',
               1859794435 => 'ASN1_TYPE_MISMATCH',
               1859794436 => 'ASN1_OVERFLOW',
               1859794437 => 'ASN1_OVERRUN',
               1859794438 => 'ASN1_BAD_ID',
               1859794439 => 'ASN1_BAD_LENGTH',
               1859794440 => 'ASN1_BAD_FORMAT',
               1859794441 => 'ASN1_PARSE_ERROR',
               1859794442 => 'ASN1_BAD_GMTIME',
               1859794443 => 'ASN1_MISMATCH_INDEF',
               1859794444 => 'ASN1_MISSING_EOC',
	     );

# This part is from *BSD.  I have in fact seen them abused as errnos instead
# of exit codes, oddly enough....
# note that OS errors override these, because on most OSes they *do* collide.

# Copyright (c) 1987, 1993
#	The Regents of the University of California.  All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. All advertising materials mentioning features or use of this software
#    must display the following acknowledgement:
#	This product includes software developed by the University of
#	California, Berkeley and its contributors.
# 4. Neither the name of the University nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.

my %sysexit = (
               64 => 'command line usage error',
               65 => 'data format error',
               66 => 'cannot open input',
               67 => 'addressee unknown',
               68 => 'host name unknown',
               69 => 'service unavailable',
               70 => 'internal software error',
               71 => "system error (e.g., can't fork)",
               72 => 'critical OS file missing',
               73 => "can't create (user) output file",
               74 => 'input/output error',
               75 => 'temp failure; user is invited to retry',
               76 => 'remote error in protocol',
               77 => 'permission denied',
               78 => 'configuration error',
	      );

my $rc = 0;
for my $err (@ARGV) {
  if ($err !~ /^-?\d+$/) {
    print STDERR "\"$err\" is not an error number\n";
    $rc = 1;
  }
  elsif (exists $krberr{$err}) {
    print 'krb5 error ', $err, ' = ', $krberr{$err}, "\n";
  }
  elsif (strerror($err) ne $err) {
    print 'os error ', $err, ' = ', strerror($err), "\n";
  }
  elsif (exists $sysexit{$err}) {
    print 'sysexits error ', $err, ' = ', $sysexit{$err}, "\n";
  }
  else {
    open TET, "translate_et $err |";
    my $s;
    my $fnd = 0;
    while (defined ($s = <TET>)) {
      chomp $s;
      if ($s =~ /^\d+\s+\((\w+)\)\.\d+\s+=\s+(.*)$/ && substr($2, 13) ne 'Unknown code ') {
	print $1, ' error ', $err, ' = ', $2, "\n";
	$fnd = 1;
      } else {
	print STDERR $s, "\n";
      }
    }
    close TET;
    if (!$fnd) {
      print 'unknown error code ', $err, "\n";
      $rc = 1;
    }
  }
}
exit $rc;
