#!/bin/sh
#
# Report free space on afs servers.
#
# Copyright (c) 2016, Sine Nomine Associates
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

CELLOPT=
usage() {
    echo "usage: afsfree [-cell <cellname>] [-noresolve]" 2>&1
    exit 1
}

while [ $# -ne 0 ]; do
    case "$1" in
    -c|-cell)
        if [ "x$2" = "x" ]; then
            echo "afsfree: missing cellname argument." 2>&1
            usage
        fi
        CELLOPT="-cell $2"
        shift
        ;;
    -n|-nor*)
        NORESOPT="-noresolve"
        ;;
    *)
        usage
        ;;
    esac
    shift
done

printf "%-24s %-8s %5s %5s %5s %s\n" host part size used avail used%
for host in `vos listaddrs -noauth $CELLOPT $NORESOPT | sort`
do
    vos partinfo -server $host -noauth |
    sed 's/\/vicep//; s/://' |
    awk -v host=$host '{
        printf("%-24s %-8s %4dG %4dG %4dG  %3d%%\n",
                host, $5, $12/1024/1024,
                ($12-$6)/1024/1024, $6/1024/1024,
                (($12-$6)/$12)*100)}'
done

