#!/usr/bin/perl -w
# search through CacheItems
use strict;

my $FHEADER_SIZE = 16;
my $FCACHE_SIZE = 80; #48;
my $buf;

open(CACHEITEMS, "<", $ARGV[0]) or die("Cannot open $ARGV[0]: $!");

read(CACHEITEMS, $buf, $FHEADER_SIZE);
my ($magic, $version, $firstCSize, $otherCSize) =
	unpack("Llll", $buf);

printf "header {\n\tmagic: 0x%08x\n\tversion: %u\n\tfirstCSize: %u\n\totherCSize: %u\n}\n",
       $magic, $version, $firstCSize, $otherCSize;

if (not defined($ARGV[1])) {
	exit(0);
}

my ($scell, $svol, $svnode, $suniq) = split /[.]/, "$ARGV[1]";

print "search for cell $scell vol $svol vnode $svnode uniq $suniq\n";

my $index = 0;

my $code;

while (($code = read(CACHEITEMS, $buf, $FCACHE_SIZE)) > 0) {
	my ($cell, $vol, $vnode, $uniq, $modtime, $versionNo_hi, $versionNo_lo, $chunk, $inode, $chunkBytes, $states) =
	    unpack("LLLLLLLLQLC", $buf);
	if ($cell == $scell && $vol == $svol && $vnode == $svnode && $uniq == $suniq) {
		print "index $index (fid $cell.$vol.$vnode.$uniq)\n";
	}
	$index++;
}
